name:                conditional-restriction-parser
version:             0.1.0.4
github:              geometalab/conditional-restriction-parser
license:             AGPL-3
license-file:        LICENSE.md
author:              Lukas Buchli
maintainer:          lukas.buchli@ost.ch
copyright:           2022 Lukas Buchli
synopsis:            Parser and interpreter of OpenStreetMap conditional restriction values
category:            Parser
description:         Please see the README on GitHub at <https://github.com/geometalab/conditional-restriction-parser#readme>

extra-source-files:
- README.md
- ChangeLog.md


dependencies:
- base >= 4.7 && < 5
# Application dependencies
- cmdargs == 0.10.21
# Library dependencies
- hourglass >= 0.2.12 && < 0.3

library:
  source-dirs: src

executables:
  conditional-restriction-parser-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - conditional-restriction-parser

tests:
  conditional-restriction-parser-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - conditional-restriction-parser
    - hspec == 2.8.5
    - QuickCheck == 2.14.2
