on: 
  push:
    tags:
      - v0.*
      - v1.*
    branches: [main]
  workflow_run:
    workflows: ["Run Tests"]
    branches: [main]
    types: 
      - completed
name: publish
jobs: 
  publish-lib-hackage:
    name: Publish Library on Hackage
    runs-on: ubuntu-latest
    environment: Publish
    steps:
      - uses: actions/checkout@v3
      - name: Publish Library on Hackage
        env:
          HACKAGE_KEY: ${{ secrets.HACKAGE_KEY }}
        run: stack upload --candidate .
    
  build-exe-linux:
    name: Build Linux Executable
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Executable
        run: |
          mkdir build
          stack install --local-bin-path build/
      - name: Publish Executable
        uses: actions/upload-artifact@v3
        with:
          name: conditional-restriction-parser
          path: build/conditional-restriction-parser-exe
